name: Interview Backend  CI

on:
  push:
    branches: [ main ]


env:
  SERVICE: Interview Backend
  GOPRIVATE: "github.com/hungaikev/*"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21.0
        id: go
      # https://github.com/mvdan/github-actions-golang
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ secrets.GH_USERNAME }}
        run: git config --global url."https://${USERNAME}:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: make test